version: "2"
services:
  app:
    container_name: service-url
    restart: always
    image: service-url:latest
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27010:27017"
